[package]
name = "iced_window_controls"
version = "0.1.0"
authors = ["Joash Agesa <joashmacer@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = {version  = "0.12.1" ,features=["advanced", "svg"]}